version: '3.7'

services:
  service-discovery:
    container_name: service-discovery
    build: ./service-discovery/.
    environment:
      - SERVICE_DISCOVERY_SERVER_PORT=${SERVICE_DISCOVERY_SERVER_PORT}
    ports:
      - ${SERVICE_DISCOVERY_SERVER_PORT}:${SERVICE_DISCOVERY_SERVER_PORT}

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway/.
    environment:
      - API_GATEWAY_SERVER_PORT=${API_GATEWAY_SERVER_PORT}
      - SERVICE_DISCOVERY_SERVER_PORT=${SERVICE_DISCOVERY_SERVER_PORT}
    ports:
      - ${API_GATEWAY_SERVER_PORT}:${API_GATEWAY_SERVER_PORT}
    depends_on:
      - service-discovery

  authentication-service:
    container_name: authentication-service
    build: ./authentication-service/.
    environment:
      - SERVICE_DISCOVERY_SERVER_PORT=${SERVICE_DISCOVERY_SERVER_PORT}
      - AUTHENTICATION_SERVICE_SERVER_PORT=${AUTHENTICATION_SERVICE_SERVER_PORT}
      - JWT_SECRET_TOKEN=${JWT_SECRET_TOKEN}
      - JWT_LIFETIME=${JWT_LIFETIME}
    depends_on:
      - api-gateway

  user-database-service:
    container_name: user-database-service
    build: ./user-database-service/.
    environment:
      - SERVICE_DISCOVERY_SERVER_PORT=${SERVICE_DISCOVERY_SERVER_PORT}
      - USER_DATABASE_SERVICE_SERVER_PORT=${USER_DATABASE_SERVICE_SERVER_PORT}
      - USER_DATABASE_SERVICE_DATABASE_NAME=${USER_DATABASE_SERVICE_DATABASE_NAME}
      - USER_DATABASE_SERVICE_GRPC_SERVER_PORT=${USER_DATABASE_SERVICE_GRPC_SERVER_PORT}
      - POSTGRESQL1_SERVER_PORT=${POSTGRESQL1_SERVER_PORT}
      - POSTGRESQL1_USERNAME=${POSTGRESQL1_USERNAME}
      - POSTGRESQL1_PASSWORD=${POSTGRESQL1_PASSWORD}
    depends_on:
      - api-gateway

  movie-service:
    container_name: movie-service
    build: ./movie-service/.
    environment:
      - SERVICE_DISCOVERY_SERVER_PORT=${SERVICE_DISCOVERY_SERVER_PORT}
      - MOVIE_SERVICE_SERVER_PORT=${MOVIE_SERVICE_SERVER_PORT}
      - JWT_SECRET_TOKEN=${JWT_SECRET_TOKEN}
      - JWT_LIFETIME=${JWT_LIFETIME}
    depends_on:
      - api-gateway

  movie-description-service:
    container_name: movie-description-service
    build: ./movie-description-service/.
    environment:
      - SERVICE_DISCOVERY_SERVER_PORT=${SERVICE_DISCOVERY_SERVER_PORT}
      - MOVIE_DESCRIPTION_SERVICE_SERVER_PORT=${MOVIE_DESCRIPTION_SERVICE_SERVER_PORT}
      - MOVIE_DESCRIPTION_SERVICE_GRPC_SERVER_PORT=${MOVIE_DESCRIPTION_SERVICE_GRPC_SERVER_PORT}
      - MOVIE_DESCRIPTION_SERVICE_ELASTICSEARCH_INDEX_MOVIE_DESCRIPTION=${MOVIE_DESCRIPTION_SERVICE_ELASTICSEARCH_INDEX_MOVIE_DESCRIPTION}
      - ELASTICSEARCH_SERVER_PORT=${ELASTICSEARCH_SERVER_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    depends_on:
      - movie-service
