version: '3.7'

services:
  service-discovery:
    container_name: service-discovery
    build: ./service-discovery/.
    environment:
      - SERVICE_DISCOVERY_SERVER_PORT=${SERVICE_DISCOVERY_SERVER_PORT}
    ports:
      - ${SERVICE_DISCOVERY_SERVER_PORT}:${SERVICE_DISCOVERY_SERVER_PORT}