spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:${SERVICE_DISCOVERY_SERVER_PORT}/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO

server:
  port: ${API_GATEWAY_SERVER_PORT}